steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'europe-west2-docker.pkg.dev/pvlive/sheffieldsolar/cloudrunplayground:$SHORT_SHA', '.']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'europe-west2-docker.pkg.dev/pvlive/sheffieldsolar/cloudrunplayground:$SHORT_SHA']

options:
  logging: CLOUD_LOGGING_ONLY

images:
  - 'europe-west2-docker.pkg.dev/pvlive/sheffieldsolar/cloudrunplayground:$SHORT_SHA'
